/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function TestModel(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("3dmodels/modeloprueba.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.013}
        >
          <group
            name="3c7371a1a9f342c5ac2edec35cdd9769fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Bouche_low001"
                  position={[-34.76, -145.685, 2.683]}
                  rotation={[-1.569, 0.172, 2.117]}
                  scale={10}
                >
                  <mesh
                    name="Bouche_low001_Organes_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Bouche_low001_Organes_0.geometry}
                    material={materials.Organes}
                  />
                </group>
                <group name="Cerveau_Low" position={[-1.229, 33.538, 2.254]}>
                  <mesh
                    name="Cerveau_Low_Organes_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cerveau_Low_Organes_0.geometry}
                    material={materials.Organes}
                  />
                </group>
                <group
                  name="Cerveau_Low001"
                  position={[-1.229, 33.538, 2.254]}
                  scale={0.711}
                >
                  <mesh
                    name="Cerveau_Low001_Organes_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cerveau_Low001_Organes_0.geometry}
                    material={materials.Organes}
                  />
                </group>
                <group
                  name="Circle009"
                  position={[-22.249, -15.584, 48.616]}
                  rotation={[-Math.PI / 2, -Math.PI / 9, 0]}
                  scale={0.421}
                >
                  <mesh
                    name="Circle009_Instruments_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle009_Instruments_0.geometry}
                    material={materials.Instruments}
                  />
                  <group name="Circle010" rotation={[Math.PI / 2, 0, 0]}>
                    <mesh
                      name="Circle010_Instruments_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Circle010_Instruments_0.geometry}
                      material={materials.Instruments}
                    />
                    <group
                      name="Sphere001"
                      position={[0, 0.034, 0]}
                      rotation={[0, 0, Math.PI / 6]}
                    >
                      <group
                        name="Circle009001"
                        position={[-0.02, -8.288, 0]}
                        rotation={[Math.PI / 2, 0, -0.087]}
                      >
                        <mesh
                          name="Circle009_Instruments_0001"
                          castShadow
                          receiveShadow
                          geometry={nodes.Circle009_Instruments_0001.geometry}
                          material={materials.Instruments}
                        />
                      </group>
                      <group
                        name="Circle011"
                        position={[-0.02, 7.197, 0]}
                        rotation={[-Math.PI / 2, 0, -3.054]}
                      >
                        <mesh
                          name="Circle011_Instruments_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Circle011_Instruments_0.geometry}
                          material={materials.Instruments}
                        />
                      </group>
                      <group
                        name="Circle012"
                        position={[-0.02, -12.052, 0]}
                        rotation={[Math.PI / 2, 0, -0.873]}
                      >
                        <mesh
                          name="Circle012_Instruments_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Circle012_Instruments_0.geometry}
                          material={materials.Instruments}
                        />
                      </group>
                      <group
                        name="Circle013001"
                        position={[-0.02, 11.769, 0]}
                        rotation={[-Math.PI / 2, 0, 0.873]}
                      >
                        <mesh
                          name="Circle013_Instruments_0001"
                          castShadow
                          receiveShadow
                          geometry={nodes.Circle013_Instruments_0001.geometry}
                          material={materials.Instruments}
                        />
                      </group>
                      <group
                        name="Circle014001"
                        position={[-0.02, 0.031, 0]}
                        rotation={[Math.PI, -0.873, Math.PI]}
                      >
                        <mesh
                          name="Circle014_Instruments_0001"
                          castShadow
                          receiveShadow
                          geometry={nodes.Circle014_Instruments_0001.geometry}
                          material={materials.Instruments}
                        />
                      </group>
                      <group
                        name="Circle015001"
                        position={[-0.02, 0.031, 0]}
                        rotation={[2.063, 0.378, 0.602]}
                      >
                        <mesh
                          name="Circle015_Instruments_0001"
                          castShadow
                          receiveShadow
                          geometry={nodes.Circle015_Instruments_0001.geometry}
                          material={materials.Instruments}
                        />
                      </group>
                      <group
                        name="Circle016001"
                        position={[-0.02, 0.031, 0]}
                        rotation={[0, -0.698, 0]}
                      >
                        <mesh
                          name="Circle016_Instruments_0001"
                          castShadow
                          receiveShadow
                          geometry={nodes.Circle016_Instruments_0001.geometry}
                          material={materials.Instruments}
                        />
                      </group>
                      <group name="Line001" position={[-0.017, -0.029, 0]}>
                        <mesh
                          name="Line001_Instruments_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Line001_Instruments_0.geometry}
                          material={materials.Instruments}
                        />
                      </group>
                      <mesh
                        name="Sphere001_Instruments_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Sphere001_Instruments_0.geometry}
                        material={materials.Instruments}
                      />
                    </group>
                  </group>
                </group>
                <group
                  name="Circle011001"
                  position={[-25.817, -12.844, -27.579]}
                  rotation={[-2.586, 0.004, -2.714]}
                  scale={0.457}
                >
                  <mesh
                    name="Circle011_Instruments_0001"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle011_Instruments_0001.geometry}
                    material={materials.Instruments}
                  />
                  <group
                    name="Circle012001"
                    rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                  >
                    <group name="Circle010001" rotation={[-Math.PI / 2, 0, 0]}>
                      <mesh
                        name="Circle010_Instruments_0001"
                        castShadow
                        receiveShadow
                        geometry={nodes.Circle010_Instruments_0001.geometry}
                        material={materials.Instruments}
                      />
                    </group>
                    <mesh
                      name="Circle012_Instruments_0001"
                      castShadow
                      receiveShadow
                      geometry={nodes.Circle012_Instruments_0001.geometry}
                      material={materials.Instruments}
                    />
                    <group name="Sphere002" rotation={[-Math.PI / 2, 0, 0]}>
                      <mesh
                        name="Sphere002_Instruments_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Sphere002_Instruments_0.geometry}
                        material={materials.Instruments}
                      />
                    </group>
                  </group>
                </group>
                <group name="Coeur_Low" position={[-3.34, -3.461, 6.482]}>
                  <mesh
                    name="Coeur_Low_Organes_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Coeur_Low_Organes_0.geometry}
                    material={materials.Organes}
                  />
                </group>
                <group
                  name="Coeur_Low001"
                  position={[-3.34, -3.461, 6.482]}
                  scale={0.649}
                >
                  <mesh
                    name="Coeur_Low001_Organes_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Coeur_Low001_Organes_0.geometry}
                    material={materials.Organes}
                  />
                </group>
                <group
                  name="Crane_Low_uv"
                  position={[-2.648, 26.217, 1.882]}
                  rotation={[0.065, 0.559, 1.512]}
                  scale={0.896}
                >
                  <mesh
                    name="Crane_Low_uv_OS_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Crane_Low_uv_OS_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Dummy001"
                  position={[11.832, -22.996, 2.483]}
                  rotation={[-Math.PI / 2, 0, 0.024]}
                >
                  <group name="Object_5">
                    <group
                      name="Object_247"
                      position={[-197.808, 89.966, -109.978]}
                      rotation={[-Math.PI / 2, 1.309, -Math.PI]}
                      scale={10}
                    />
                    <skinnedMesh
                      name="Object_248"
                      geometry={nodes.Object_248.geometry}
                      material={materials.Bras_Ext}
                      skeleton={nodes.Object_248.skeleton}
                    />
                    <skinnedMesh
                      name="Object_249"
                      geometry={nodes.Object_249.geometry}
                      material={materials.Bras_Int}
                      skeleton={nodes.Object_249.skeleton}
                    />
                    <group
                      name="Object_250"
                      position={[-197.808, 89.966, -109.978]}
                      rotation={[-Math.PI / 2, 1.309, -Math.PI]}
                      scale={10}
                    />
                    <skinnedMesh
                      name="Object_251"
                      geometry={nodes.Object_251.geometry}
                      material={materials.Bras_Ext}
                      skeleton={nodes.Object_251.skeleton}
                    />
                    <skinnedMesh
                      name="Object_252"
                      geometry={nodes.Object_252.geometry}
                      material={materials.Bras_Int}
                      skeleton={nodes.Object_252.skeleton}
                    />
                    <group
                      name="Object_253"
                      position={[-197.808, 89.966, -109.978]}
                      rotation={[-Math.PI / 2, 1.309, -Math.PI]}
                      scale={10}
                    />
                    <skinnedMesh
                      name="Object_254"
                      geometry={nodes.Object_254.geometry}
                      material={materials.Bras_Ext}
                      skeleton={nodes.Object_254.skeleton}
                    />
                    <skinnedMesh
                      name="Object_255"
                      geometry={nodes.Object_255.geometry}
                      material={materials.Bras_Int}
                      skeleton={nodes.Object_255.skeleton}
                    />
                    <group
                      name="Object_256"
                      position={[-197.808, 89.966, -109.978]}
                      rotation={[-Math.PI / 2, 1.309, -Math.PI]}
                      scale={10}
                    />
                    <skinnedMesh
                      name="Object_257"
                      geometry={nodes.Object_257.geometry}
                      material={materials.Bras_Ext}
                      skeleton={nodes.Object_257.skeleton}
                    />
                    <skinnedMesh
                      name="Object_258"
                      geometry={nodes.Object_258.geometry}
                      material={materials.Bras_Int}
                      skeleton={nodes.Object_258.skeleton}
                    />
                    <group
                      name="Object_259"
                      position={[-197.808, 89.966, -109.978]}
                      rotation={[-Math.PI / 2, 1.309, -Math.PI]}
                      scale={10}
                    />
                    <skinnedMesh
                      name="Object_260"
                      geometry={nodes.Object_260.geometry}
                      material={materials.Bras_Ext}
                      skeleton={nodes.Object_260.skeleton}
                    />
                    <skinnedMesh
                      name="Object_261"
                      geometry={nodes.Object_261.geometry}
                      material={materials.Bras_Int}
                      skeleton={nodes.Object_261.skeleton}
                    />
                    <group
                      name="Object_262"
                      position={[-197.808, 89.966, -109.978]}
                      rotation={[-Math.PI / 2, 1.309, -Math.PI]}
                      scale={10}
                    />
                    <skinnedMesh
                      name="Object_263"
                      geometry={nodes.Object_263.geometry}
                      material={materials.Bras_Ext}
                      skeleton={nodes.Object_263.skeleton}
                    />
                    <skinnedMesh
                      name="Object_264"
                      geometry={nodes.Object_264.geometry}
                      material={materials.Bras_Int}
                      skeleton={nodes.Object_264.skeleton}
                    />
                    <primitive object={nodes._rootJoint} />
                  </group>
                </group>
                <group
                  name="EYE_L001"
                  position={[-7.956, 30.417, 8.847]}
                  rotation={[-1.587, 0.011, -0.664]}
                >
                  <mesh
                    name="EYE_L001_Organes_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.EYE_L001_Organes_0.geometry}
                    material={materials.Organes}
                  />
                </group>
                <group
                  name="EYE_R001"
                  position={[-11.061, 30.966, 3.653]}
                  rotation={[-1.6, -0.001, -0.841]}
                >
                  <mesh
                    name="EYE_R001_Organes_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.EYE_R001_Organes_0.geometry}
                    material={materials.Organes}
                  />
                </group>
                <group
                  name="FOND_ROND001"
                  position={[-0.218, -68.636, 2.523]}
                  rotation={[-Math.PI / 2, 0, -0.479]}
                  scale={1.103}
                />
                <group
                  name="Fractures_Dos_low"
                  position={[0, -148.116, 11.509]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Fractures_Dos_low_Body_Ext_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Fractures_Dos_low_Body_Ext_0.geometry}
                    material={materials.Body_Ext}
                  />
                  <mesh
                    name="Fractures_Dos_low_body_Int_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Fractures_Dos_low_body_Int_0.geometry}
                    material={materials.body_Int}
                  />
                </group>
                <group
                  name="Group002"
                  position={[-13.923, 15.796, 36.412]}
                  rotation={[1.311, 0.049, -0.407]}
                  scale={0.349}
                >
                  <group
                    name="Circle014"
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={1.397}
                  >
                    <mesh
                      name="Circle014_Instruments_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Circle014_Instruments_0.geometry}
                      material={materials.Instruments}
                    />
                  </group>
                  <group
                    name="Circle015"
                    rotation={[Math.PI / 2, -1.57, 0]}
                    scale={1.397}
                  >
                    <mesh
                      name="Circle015_Instruments_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Circle015_Instruments_0.geometry}
                      material={materials.Instruments}
                    />
                  </group>
                  <group
                    name="Circle016"
                    rotation={[-Math.PI, 0, 0]}
                    scale={1.397}
                  >
                    <mesh
                      name="Circle016_Instruments_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Circle016_Instruments_0.geometry}
                      material={materials.Instruments}
                    />
                  </group>
                  <group
                    name="Circle017"
                    position={[0, 0, 16.543]}
                    rotation={[-Math.PI, 0, 0]}
                    scale={1.397}
                  >
                    <mesh
                      name="Circle017_Instruments_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Circle017_Instruments_0.geometry}
                      material={materials.Instruments}
                    />
                  </group>
                  <group
                    name="Circle018"
                    position={[0, 0, -16.543]}
                    rotation={[0, 0, Math.PI]}
                    scale={1.397}
                  >
                    <mesh
                      name="Circle018_Instruments_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Circle018_Instruments_0.geometry}
                      material={materials.Instruments}
                    />
                  </group>
                  <group
                    name="Sphere003"
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={1.397}
                  >
                    <mesh
                      name="Sphere003_Instruments_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Sphere003_Instruments_0.geometry}
                      material={materials.Instruments}
                    />
                  </group>
                </group>
                <group
                  name="Group004"
                  position={[-0.761, 20.559, 8.515]}
                  rotation={[-Math.PI / 2, 0, 0.611]}
                  scale={0.195}
                >
                  <group
                    name="Circle013"
                    position={[0, 0, 18.356]}
                    rotation={[Math.PI / 2, 0, 0]}
                  >
                    <mesh
                      name="Circle013_Instruments_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Circle013_Instruments_0.geometry}
                      material={materials.Instruments}
                    />
                  </group>
                  <group
                    name="Plane002"
                    position={[0, 0, -0.947]}
                    rotation={[Math.PI / 2, 0, 0]}
                  >
                    <mesh
                      name="Plane002_Instruments_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Plane002_Instruments_0.geometry}
                      material={materials.Instruments}
                    />
                  </group>
                </group>
                <group
                  name="Group005"
                  position={[-4.191, 49.897, -44.678]}
                  rotation={[-1.288, -0.28, -1.039]}
                  scale={0.426}
                >
                  <group
                    name="Box001"
                    position={[-0.127, 8.174, -8.113]}
                    rotation={[Math.PI / 2, 0, 0]}
                  >
                    <mesh
                      name="Box001_Instruments_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Box001_Instruments_0.geometry}
                      material={materials.Instruments}
                    />
                  </group>
                  <group
                    name="Circle019"
                    position={[-0.127, 5.451, -8.397]}
                    rotation={[-Math.PI / 4, 0, 0]}
                  >
                    <group name="Object_293" position={[0, -9.064, -0.353]}>
                      <mesh
                        name="Circle019_Instruments_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Circle019_Instruments_0.geometry}
                        material={materials.Instruments}
                      />
                    </group>
                  </group>
                  <group
                    name="Circle020"
                    position={[-8.58, 7.882, -8.069]}
                    rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                  >
                    <group name="Object_298">
                      <mesh
                        name="Circle020_Instruments_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Circle020_Instruments_0.geometry}
                        material={materials.Instruments}
                      />
                    </group>
                  </group>
                  <group
                    name="Circle021"
                    position={[-0.127, 4.895, -8.34]}
                    rotation={[-Math.PI / 4, 0, 0]}
                    scale={0.457}
                  >
                    <group name="Object_301">
                      <mesh
                        name="Circle021_Instruments_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Circle021_Instruments_0.geometry}
                        material={materials.Instruments}
                      />
                    </group>
                  </group>
                  <group
                    name="Cylinder001"
                    position={[-0.127, 7.394, 0.679]}
                    rotation={[Math.PI / 2, 0, 0]}
                  >
                    <mesh
                      name="Cylinder001_Instruments_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cylinder001_Instruments_0.geometry}
                      material={materials.Instruments}
                    />
                  </group>
                  <group
                    name="Line002"
                    position={[0.029, -2.584, -1.101]}
                    rotation={[-2.356, -Math.PI / 2, 0]}
                  >
                    <group name="Object_304" position={[0, 2.088, 0]}>
                      <mesh
                        name="Line002_Instruments_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Line002_Instruments_0.geometry}
                        material={materials.Instruments}
                      />
                    </group>
                  </group>
                  <group
                    name="Object015"
                    position={[-0.127, 6.826, 0.667]}
                    rotation={[Math.PI / 2, 0, 0]}
                  >
                    <mesh
                      name="Object015_Instruments_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object015_Instruments_0.geometry}
                      material={materials.Instruments}
                    />
                  </group>
                  <group
                    name="Plane003"
                    position={[-0.127, 6.56, 0.667]}
                    rotation={[Math.PI / 2, 0, -0.611]}
                    scale={[0.404, 1, 1]}
                  >
                    <mesh
                      name="Plane003_Instruments_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Plane003_Instruments_0.geometry}
                      material={materials.Instruments}
                    />
                  </group>
                  <group
                    name="Tube001"
                    position={[-0.127, 8.174, 0.667]}
                    rotation={[Math.PI / 2, 0, 0]}
                  >
                    <mesh
                      name="Tube001_Instruments_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Tube001_Instruments_0.geometry}
                      material={materials.Instruments}
                    />
                  </group>
                </group>
                <group
                  name="Group006"
                  position={[-8.281, 21.965, -3.279]}
                  rotation={[-Math.PI / 2, 0, Math.PI / 9]}
                  scale={0.195}
                >
                  <group
                    name="Circle022"
                    position={[0, 0, 18.356]}
                    rotation={[Math.PI / 2, 0, 0]}
                  >
                    <mesh
                      name="Circle022_Instruments_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Circle022_Instruments_0.geometry}
                      material={materials.Instruments}
                    />
                  </group>
                  <group
                    name="Plane004"
                    position={[0, 0, -0.947]}
                    rotation={[Math.PI / 2, 0, 0]}
                  >
                    <mesh
                      name="Plane004_Instruments_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Plane004_Instruments_0.geometry}
                      material={materials.Instruments}
                    />
                  </group>
                </group>
                <group
                  name="Main_Low007"
                  position={[-64.168, -5.37, -105.241]}
                  rotation={[-Math.PI / 2, 1.309, -Math.PI]}
                  scale={10}
                />
                <group
                  name="Main_Low008"
                  position={[-64.168, -5.37, -105.241]}
                  rotation={[-Math.PI / 2, 1.309, -Math.PI]}
                  scale={10}
                />
                <group
                  name="Main_Low009"
                  position={[-64.168, -5.37, -105.241]}
                  rotation={[-Math.PI / 2, 1.309, -Math.PI]}
                  scale={10}
                />
                <group
                  name="Main_Low010"
                  position={[-64.168, -5.37, -105.241]}
                  rotation={[-Math.PI / 2, 1.309, -Math.PI]}
                  scale={10}
                />
                <group
                  name="Main_Low011"
                  position={[-64.168, -5.37, -105.241]}
                  rotation={[-Math.PI / 2, 1.309, -Math.PI]}
                  scale={10}
                />
                <group
                  name="Main_Low012"
                  position={[-64.168, -5.37, -105.241]}
                  rotation={[-Math.PI / 2, 1.309, -Math.PI]}
                  scale={10}
                />
                <group name="Muscles004" position={[0, 11.532, 6.061]}>
                  <group name="Object_327" position={[39.516, 10.765, 5.449]}>
                    <mesh
                      name="Muscles004_Muscle_Ext_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Muscles004_Muscle_Ext_0.geometry}
                      material={materials.Muscle_Ext}
                    />
                    <mesh
                      name="Muscles004_Muscle_Int_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Muscles004_Muscle_Int_0.geometry}
                      material={materials.Muscle_Int}
                    />
                  </group>
                </group>
                <group name="Muscles005" position={[0, -8.158, 6.881]}>
                  <group name="Object_331" position={[39.516, 30.454, 4.628]}>
                    <mesh
                      name="Muscles005_Muscle_Ext_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Muscles005_Muscle_Ext_0.geometry}
                      material={materials.Muscle_Ext}
                    />
                    <mesh
                      name="Muscles005_Muscle_Int_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Muscles005_Muscle_Int_0.geometry}
                      material={materials.Muscle_Int}
                    />
                  </group>
                </group>
                <group name="Muscles006" position={[0, 11.867, 5.222]}>
                  <group name="Object_335" position={[39.516, 10.429, 6.287]}>
                    <mesh
                      name="Muscles006_Muscle_Ext_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Muscles006_Muscle_Ext_0.geometry}
                      material={materials.Muscle_Ext}
                    />
                    <mesh
                      name="Muscles006_Muscle_Int_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Muscles006_Muscle_Int_0.geometry}
                      material={materials.Muscle_Int}
                    />
                  </group>
                </group>
                <group name="Muscles007" position={[0, 6.03, 3.421]}>
                  <group name="Object_339" position={[39.516, 16.266, 8.05]}>
                    <mesh
                      name="Muscles007_Muscle_Ext_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Muscles007_Muscle_Ext_0.geometry}
                      material={materials.Muscle_Ext}
                    />
                    <mesh
                      name="Muscles007_Muscle_Int_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Muscles007_Muscle_Int_0.geometry}
                      material={materials.Muscle_Int}
                    />
                  </group>
                </group>
                <group name="Retopo_001" position={[0, 42.482, 11.509]}>
                  <group name="Object_315" position={[24.221, 0, 0]}>
                    <mesh
                      name="Retopo_001_Body_Ext_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Retopo_001_Body_Ext_0.geometry}
                      material={materials.Body_Ext}
                    />
                    <mesh
                      name="Retopo_001_body_Int_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Retopo_001_body_Int_0.geometry}
                      material={materials.body_Int}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("3dmodels/modeloprueba.glb");

export default TestModel;
