/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function ModelANLogo(props) {
  const { nodes, materials } = useGLTF("./animanoir-logo-3d-v2.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Curve.geometry}
        material={nodes.Curve.material}
        position={[-0.009, -0.01, 0.25]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={60}
      />
    </group>
  );
}

useGLTF.preload("/animanoir-logo-3d-v2.glb");
