/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF, meshBounds } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import * as THREE from "three";

export function ModelANLogo(props) {
  const { gl } = useThree();
  const { nodes, materials } = useGLTF("./animanoir-logo-3d-v2.glb");
  const meshRef = useRef();

  useFrame((state, delta) => {
    if (meshRef.current) {
      meshRef.current.rotation.z += delta * -0.3;
    }
  });

  const clickHandler = () => {
    meshRef.current.material.color.set(
      `hsl(${Math.random() * 360}, 100%, 80%)`
    );

    console.log("click");
  };

  return (
    <>
      <mesh
        ref={meshRef}
        raycast={meshBounds}
        geometry={nodes.Curve.geometry}
        material={nodes.Curve.material}
        position={[0, -1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={60}
        onPointerOver={(e) => {
          gl.domElement.style.cursor = "pointer";
          clickHandler();
        }}
        onPointerOut={(e) => {
          gl.domElement.style.cursor = "auto";
        }}
      >
        <meshStandardMaterial
          metalness={1}
          roughness={0.1}
        ></meshStandardMaterial>
      </mesh>
    </>
  );
}

useGLTF.preload("/animanoir-logo-3d-v2.glb");
