/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function ModelANLogo(props) {
  const { nodes, materials } = useGLTF("./animanoir-logo-3d-v2.glb");
  const meshRef = useRef(); // Agregar esta línea para tener una referencia al mesh

  // Agregar useFrame para actualizar la rotación en cada fotograma
  useFrame((state, delta) => {
    if (meshRef.current) {
      meshRef.current.rotation.z += delta * -0.3; // Rotar lentamente en el eje Y
    }
  });

  return (
    <>
      <mesh
        ref={meshRef} // Asignar la referencia aqu
        geometry={nodes.Curve.geometry}
        material={nodes.Curve.material}
        position={[0, -1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={60}
      >
        <meshStandardMaterial metalness={1} roughness={0.1} color={"#fff"} />
      </mesh>
    </>
  );
}

useGLTF.preload("/animanoir-logo-3d-v2.glb");
